// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProsesKontrolWeb.Server.Data;

#nullable disable

namespace ProsesKontrolWeb.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230912094646_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProsesKontrolWeb.Shared.Models.ProsesKontrolModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HataTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontrolMetodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Operator")
                        .HasColumnType("bit");

                    b.Property<string>("OperatorKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProsesId")
                        .HasColumnType("int");

                    b.Property<bool?>("ProsesKontrolSorumlusu")
                        .HasColumnType("bit");

                    b.Property<string>("ProsesSorumlusuKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProsesKontrolModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HataTipi = "1",
                            KontrolMetodu = "KM",
                            Operator = true,
                            OperatorKontrol = "sda",
                            ProsesKontrolSorumlusu = false,
                            ProsesSorumlusuKontrol = "sdasda",
                            Standart = "Standart"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
